### ISSUE TITLE
Poor docs for OMV5

### ISSUE THREAD

**Issue by replay111** [OpenMediaVault-Plugin-Developers/docs#25]
This doc is totally outdated and based on OMV4: https://github.com/OpenMediaVault-Plugin-Developers/docs/blob/master/Getting_Started-OMV5.pdf

There is no longer such storage like /srv/dev-disk-by-label - not this is a hash not a human readable path,
also VBox is no longer support in favour of Cockipit and its VMs...

**Comment by ryecoaaron** [comment]
The guide was edited about a month ago.  It is not for OMV 4.x.

disk-by-label was just removed a few weeks ago from OMV.  The guide does need to updated but that doesn't mean everything else is wrong.

The reference to virtualbox is for running OMV in a VM not VMs on OMV.  That is supported.

**Comment by flmaxey** [comment]
> There is no longer such storage like /srv/dev-disk-by-label -

Thanks.  I appreciate the complement.  If you found **one** (1) error in 90 pages, which is due to a _recent_ change I am, without doubt, doing very well.

But you're being overly critical, don't you think?  While I appreciate the heads up on a change I missed, **one** (1) error doesn't make a 90 page document "poor".  That would be a rather lofty standard.

But, before being hasty, let's consider:
The majority of the installed OMV5 user base have hard drives that are installed "by label".  Further, OMV updates don't change existing "by label" drive mount points to UUID.
Also of note is that a new installation with the latest ISO (OMV5 5.5.11) still sets drive mount points "by label".  It's only when 5.5.11 is fully updated  to 5.6.2-1 (which some users don't do) "AND" a new disk is formatted, when UUID is used for the mount point.  The above represents a good number of conditions to be meet before the User Guide becomes "poor".

It should be noted that the **vast majority** of the installed OMV5 user base may use this document and the wiki for "future reference".  That means the document, as it's written, shouldn't be changed just yet, should it?  Maybe a note should be added, regarding the UUID change for mid-stream OM5  installations.  That seems to make sense - I'm sure you'd agree.
__________________________________________________

> VBox is no longer support in favour of Cockipit and its VMs..

I'm not sure what this is about.  The only mention of Virtual Box is -> [here](https://openmediavault.readthedocs.io/en/5.x/new_user_guide/newuserguide.html#virtual-box).  This section mentions building "OMV as a VM" for testing purposes, referencing "a windows client" with 6GB and lots of hard disk space, to be used (obviously) as the VM host.  There's nothing that suggests VB is supported.

**Comment by flmaxey** [comment]
With regard to UUID's:
Appropriate notes were added to the sections for Rsync backup, WinSCP, and shutting down the quota service.  (Where UUID's apply.)

Regarding Virtual Box:
Text was slightly rewritten to more strongly indicate, _for learning purposes only_, that OMV is to be a **test VM** on Windows Client host.
