### ISSUE TITLE
Don't recommend balena etcher (includes spyware and adware) for writing images

### ISSUE THREAD

**Issue by rradar** [OpenMediaVault-Plugin-Developers/docs#9]
I know the guide is for noob's (@flmaxey) using windows (hopefully not 7 like the author of the guide :roll_eyes:) so it's even more important to don't recommend software which is known to spy their users and comes bundled with adware (or "promotend content" the authors like to call it :man_facepalming:).

Their is various FOSS software out their which does exactly the same etcher do (writing and verify) like [usbimager](https://gitlab.com/bztsrc/usbimager) for example. Difference is mainly that usbimager is less 300KB in size while etcher comes in a package of around 400MB... analytics, tracking and more needs space!

**Comment by flmaxey** [comment]
First:  Note that I have a bit of experience in writing and teaching classes.
Second: I'm promoting nothing but OMV, "if" users decide that they want to use it.  

I offer users a potential install process, written in a walk through format.  The "walk through" format does not work well with a couple, a few, or several paths to get to the same goal.  What is written and the utilities involved was verified, step by step, to work.  Educated users are free to use any equivalent utility they chose.  No one is forced to use anything.

Not to pat my own back or Aaron's:
10's of thousands of users (literally) have used Aaron's install script, and these guides, without a problem.  The fact that negative feedback is nearly **non-existent**, with such wide spread usage, is remarkable.  In fact, the only issues encountered tend to come from users who do NOT use these guides.

But I'll acknowledge, as it is with many things in life, there's more that one way to do the same thing.  Since you have ideas for guide(s) that you seem to feel strongly about, you're free to write your own versions.  You can even use mine as a start - they're not copyrighted so please feel free.  Who knows?  After they're reviewed, management may decide to use your guides instead.  (But realize that comes with some responsibility of ongoing maintenance.)

**Edit: Etcher is recommended by Armbian for the installation of their image.**

**Comment by ryecoaaron** [comment]
I would be all for switching to usbimager since it is open source, checksums, and works on Windows (even on XP the comparison chart says).

Unfortunately, it doesn't support 7-zip (Armbian default compression, maybe author can add the support?) and it doesn't support/detect my mmc device on my Xubuntu 19.10 laptop.  I will have to file a couple of issues.

**Comment by rradar** [comment]
@ryecoaaron it does support 7-zip. I flashed compressed 7-zip images with usbimager (v1.0.0) without problems.

Btw: Here is a request (which needs backers) to set **verify** to **on** as **default** setting https://gitlab.com/bztsrc/usbimager/-/issues/5

**Comment by ryecoaaron** [comment]
Ok.  I didn't try it since the project readme and manual only mention:

Can read compressed images on-the-fly: .gz, .bz2, .xz
Can read archives on-the-fly: .zip (PKZIP and ZIP64) (*)

**Comment by rradar** [comment]
Actually I think I'm wrong. Didn't checked the results after. Now I looked and it's not usable so I guess just the archive was written to flash.

https://gitlab.com/bztsrc/usbimager/-/issues/7 -zip :dancer:

**Comment by rradar** [comment]
@flmaxey I see that new docs are up but from a short check (armbian omv installation) the **issue still exists**: promoting spyware/adware bundled software called balena etcher to novice users :disappointed:

**Comment by flmaxey** [comment]
Ok...

There's more than one package out there that will work for this purpose.  My personal preference was to use win32diskimager but, in the initial image flashing process, a second step is required for verification of a burn.  For first time setup, where new users are "wobbling", the second step was a strong vote against win32diskimager.   When writing a document for the masses, reducing the number of steps where things can go wrong is important.

As I looked over USB Image Tool:
There doesn't appear to be any "easy to use" function for testing the image, against the source, after the image is burned.  Why is that important?  Because users will attempt to use old SD-cards that may be defective, without knowing it, or buy cheap generic SD-cards on-line or out of a sale bin.  
Roughly half of the problems with SBC's, that land on OMV's forum, are related to crap or failing SD-cards.  This is where Etcher shines, with no user input required.  Click a button, the image is burned AND verified, which has the secondary effect of checking the integrity of the area written in the SD-card.  A clean flash is guaranteed or, at least, a failure is known.

But the bottom line reason why Etcher is used, is because the Armbian project recommends it.  (Note that OMV is installed **on top** of their images.)  Armbian's image distributions encompass the greatest majority of different SBC models, so it doesn't make sense to buck their recommendation.  Recommending something different would only confuse matters. 

Tell you what, if you can convince the Armbian project that they should recommend another media flashing application, I'll go along with them.

**Comment by rradar** [comment]
> As I looked over USB Image Tool:
There doesn't appear to be any "easy to use" function for testing the image, against the source, after the image is burned.

If you talk about [USBImager](https://gitlab.com/bztsrc/usbimager/) this "easy to use" function is called **Verify** and enabled by default

![image](https://user-images.githubusercontent.com/34582688/79621454-6659b580-810b-11ea-87bd-0c0214d5e416.png)


> This is where Etcher shines, with no user input required

Etcher has a lot of this things where **no user input is required: tracking, ads, analytics** - very shiny indeed :sparkles: 

> Tell you what, if you can convince the Armbian project that they should recommend another media flashing application, I'll go along with them.

You know [Igor (founder of armbian)](https://forum.armbian.com/topic/13421-need-your-help-what-else-beside-etcher/?tab=comments#comment-98778)?

> **I say we go and change the recommendation to USBImager and leave Etcher there as "also usable, but includes spyware"**
